# capitalize_method = "my naem is aditya porwal".capitalize()
# print(capitalize_method)
# casefold_method = "hello rohan how are you".casefold()
# print(casefold_method)
# center_method = "this is center method".center(50,'#')
# print(center_method)
# count_method = "this is count method".count('i',0,6)
# print(count_method)
# find_method = "this is find method".find('find',0,14)
# print(find_method)
# endswith_method = "this is endswith method".endswith('d',0,22)
# print(endswith_method)
# expandtabs_method = "this\tis\texpandtabs\tmethod".expandtabs(9)
# print(expandtabs_method)
# index_mehod = "this is index method in python".index("python",0,80)
# print(index_mehod)
# rindex_method = "this is rindex method and is the best method".rindex('best',0,88)
# print(rindex_method)
# isalnum_method = "this".isalnum()
# print(isalnum_method)
# isalpha_method = "thisisisalphamethod".isalpha()
# print(isalpha_method)
# isnumeric_method = "121334343".isnumeric()
# print(isnumeric_method)
# isdecimal_method = "5".isdecimal()
# print(isdecimal_method)
# isdigit_method = "3843".isdigit()
# print(isdigit_method)
# isidentifier_method = "dfd667".isidentifier()
# print(isidentifier_method)
# islower_method = "this is islower method".islower()
# print(islower_method)
# isupper_method = "THIS IS ISUPPER METHOD".isupper()
# print(isupper_method)
# isprintable_method = "this is is $ printable % method".isprintable()
# print(isprintable_method)
# istitle_method = "This Is Istitle Method".istitle()
# print(istitle_method)
# join_method = ['this', 'is', 'a', 'aditya', 'porwal']
# print('_'.join(join_method))
# print(' '.join(join_method))
# strip_method = "this is strip method"
# print(strip_method.strip('this is'))
# replace_method = "this is replace replace method".replace('replace','REPLACE')
# print(replace_method)
# find_method = "this is rfind method"
# print(find_method.find('is',0,34))
# rfind_method = "this is rfind method"
# print(rfind_method.rfind('is'))
# ljust_method = "hello".ljust(9,'#')
# print(ljust_method)
# rust_method = "Hello_aditya".rjust(16,'#')
# print(rust_method)
# rsplit_method = "apple , banana , mango , orange".split(',',2)
# print(rsplit_method)
# str = "this \t is \t splitline \t method"
# print(str.splitlines(False))
# zfill_method = "this is zfill method".zfill(25)
# print(len(zfill_method))
# print(zfill_method)
# name = "my name aditya porwal and ashutosh porwal".rpartition('aditya porwal')
# print(name)
# name = "aditya porwal".strip('adpo')#aditya pa
# print(name)
# name = "aditya"
# print(name[-2::-1])

