capitalize_method = "my naem is aditya porwal".capitalize()
print(capitalize_method)
casefold_method = "hello rohan how are you".casefold()
print(casefold_method)
center_method = "this is center method".center(50,'#')
print(center_method)
count_method = "this is count method".count('i',0,6)
print(count_method)
find_method = "this is find method".find('find',0,14)
print(find_method)
endswith_method = "this is endswith method".endswith('d',0,22)
print(endswith_method)
expandtabs_method = "this\tis\texpandtabs\tmethod".expandtabs(9)
print(expandtabs_method)